config/routes.rb
Rails.application.routes.draw do

  resources :artists

  get 'home', to: 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'test', to: 'static_pages#test'

  root 'static_pages#home'

end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :string
#  image_url   :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Artist < ActiveRecord::Base
  has_many :songs
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  title      :string
#  length     :string
#  genre      :string
#  artist_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Song < ActiveRecord::Base
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = get_artist
  end

  def new
    @artist = Artist.new
  end

  def edit
    @artist = get_artist
  end


  def update
    @artist = get_artist
    if @artist.update(artist_params)
      redirect_to artist_path(@artist), notice: "Artist removed"
    else
      render "edit"
    end
  end


private

  # for great safety!
  def artist_params
    params.require(:artist).permit(:name, :image_url, :description)
  end

  def get_artist
    Artist.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<div class='col-md-12'>

  <div class="table-responsive">
    <h1 style="color:#666"> Our Cool Artists </h1>

    <table class="table table-hover">

      <tr class="small">
        <th> Artist Image </th>
        <th> Name </th>
        <th> Bio </th>
        <th> Actions </th>
      </tr>

      <!-- now rows for each artist, looping over artists -->
      <% @artists.each do |artist| %>
      <tr>
        <td class="col-md-2"> <%= image_tag(artist.image_url, class: 'img-thumbnail img-responsive')  %> </td>
        <td> <%= artist.name %> </td>
        <td> <%= artist.description %> </td>
        <td>
          <%= link_to( 'show', artist_path(artist), class: 'btn btn-default btn-xs') %>
          <%= link_to 'edit', edit_artist_path(artist), class: 'btn btn-success btn-xs' %>
          <%= link_to 'Delete', artist, method: :delete, data: { confirm: 'You sure honey?' }, class: 'btn btn-warning btn-xs' %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
  <div class='well'>
    <%= link_to 'Add New Artist', new_artist_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/artists/new.html.erb
<div class="container col-xs-12">
<div class="panel panel-default">
  <div class="panel-heading">
    <h1> Add a new artist </h1>
  </div>
  <div class="panel-body">
    <%= simple_form_for @artist do |f| %>
      <%= f.input :name, label: false, input_html: { placeholder: 'Name' } %>
      <%= f.input :description, label: false, as: :text, input_html: { placeholder: "Artist Bio" } %>
      <%= f.input :image_url, label:false, input_html: { placeholder: 'Image url' } %>
      <%= f.submit "Submit".html_safe, class: "btn btn-lg btn-danger" %>
    <% end %>
  </div>
</div>
</div>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/layouts/_main_nav.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a href="/artists">Artists</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->



</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<%= render 'layouts/main_nav' %>

<%= yield %>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPage#about</h1>
<p>Find me in app/views/static_page/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Welcome to Hype Music!!!</h1>
<p><%= link_to 'Check out our Music', test_path, class: 'btn btn-lg btn-warning' %></p>

app/views/static_pages/test.html.erb
    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Music App</h1>
                        <p class="intro-text">A collection of great music</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About Grayscale</h2>
                <p>Grayscale is a free Bootstrap 3 theme created by Start Bootstrap. It can be yours right now, simply download the template on <a href="http://startbootstrap.com/template-overviews/grayscale/">the preview page</a>. The theme is open source, and you can use it for any purpose, personal or commercial.</p>
                <p>This theme features stock photos by <a href="http://gratisography.com/">Gratisography</a> along with a custom Google Maps skin courtesy of <a href="http://snazzymaps.com/">Snazzy Maps</a>.</p>
                <p>Grayscale includes full HTML, CSS, and custom JavaScript files along with LESS files for easy customization.</p>
            </div>
        </div>
    </section>